### ISSUE TITLE
Problems and needed improvements

### ISSUE THREAD

**Issue by georgeserbezov** [MapCreatorEU/api-wrapper#63]
**Console**
- [x] For attach and detach ALL organisations to an asset, it can be made 2 methods that handle this operation.    
- [x] For CrudSetBase, when getting child items with _listResource, get the Child.length for perPage items, so it can get all child items for a set
- [x] Issue with ImageHandler, can not upload. Possible problem in ImageHandler.js on line 91 instead of this._api.token.toString(), might be this._api._auth.token.toString()
Error: 
```
TypeError: undefined is not an object (evaluating '_this2._api.token.toString')
```
- [x] There must be a function for preview image of Mapstyle. Ask @beschoenen 

**Job Monitor**
- [x] For selected job overview fix URLs - Preview, Archive, Log, Directory.   
- [ ] ~For Job overview of selected job, make a model which will retrieve all the data needed.~    
- [ ] ~For job results list, make model which will accept job status or Hide internal status and retrieve all the information needed.~

**Comment by Mechazawa** [comment]
Can you give me an example?

**Comment by Mechazawa** [comment]
> For attach and detach ALL organisations to an asset, it can be made 2 methods that handle this operation.

So  for attaching a resource to all Organizations? You should be able to just pass them as an array to the method.

**Comment by Mechazawa** [comment]
> For job results list, make model which will accept job status or Hide internal status and retrieve all the information needed.

What information do you want? Can you give me an example of what you're trying to accomplish?

**Comment by Mechazawa** [comment]
>For Job overview of selected job, make a model which will retrieve all the data needed.
What data is known and what data are you trying to fetch and from where?

**Comment by georgeserbezov** [comment]
```
TypeError: undefined is not an object (evaluating 'this.organisation.attach(user).then')
```

**Comment by georgeserbezov** [comment]
URLs are still not working @Mechazawa 

```
lastArchiveUrl: "/jobs/{id}/revisions/last/result/archive"
```

**Comment by Mechazawa** [comment]
Is fixed in the last revision

**Comment by Mechazawa** [comment]
`CrudBase` are module level exported so you should be able to make your own models for job info

**Comment by Mechazawa** [comment]
Models can be passed into the `api.static` method
