### ISSUE TITLE
Create Contract problem

### ISSUE THREAD

**Issue by georgeserbezov** [MapCreatorEU/api-wrapper#82]
When creating a contract the date formatter is not correct. When the date is set to January it shows 00 and so on for every month shows the previous number of the months.
Example:
```
{"name":"Test3",
 "organisation_id":5, 
 "credits":"2500",
 "auto_renewal":true,
 "date_start":"18-00-01 11:06:00",
 "date_end":"18-01-04 11:06:00"}
```

**Comment by Mechazawa** [comment]
Odd, I'll look into it tomorrow.

**Comment by Mechazawa** [comment]
:tada:
