### ISSUE TITLE
New routes for linked all and none users

### ISSUE THREAD

**Issue by beschoenen** [MapCreatorEU/api-wrapper#84]
`{resource}/{id}/organisations/all`

A `post` to this route will check all.
A `delete` to this route will check none.

the resources that use this are:
- Colors
- DimensionSets
- Features
- FontFamilies
- JobTypes
- Layers
- MapstyleSets
- SvgSets

**Comment by Mechazawa** [comment]
Something like this?
`attachAllOrganisations` and `detachAllOrganisations`?

**Comment by beschoenen** [comment]
Not sure what the syntax is right now, But maybe `organisations.detachAll()`?

**Comment by Mechazawa** [comment]
That sounds like a better syntax, making organisations a proxy

**Comment by beschoenen** [comment]
This will be added to all resources after an organisation as well

`/organisations/{id}/job-types/all`

**Comment by Mechazawa** [comment]
Added in #87
