### ISSUE TITLE
Possibility to set the order of organisation assets.

### ISSUE THREAD

**Issue by georgeserbezov** [MapCreatorEU/api-wrapper#95]
Should be possible to set the ordering of the assets of organisation.

![screen shot 2018-01-11 at 10 51 29](https://user-images.githubusercontent.com/14870033/34819240-7a166c06-f6bd-11e7-98dc-8e73be93cdd9.png)

**Comment by Mechazawa** [comment]
I still don't know how that would be represented in the studio UI.

**Comment by Mechazawa** [comment]
was that field added manually to the database?
